var people = {
  "cb" : {
    "President" : [
      {
       "name": "Joe Abdo",
       "photo": "https://snworksceo.imgix.net/dpn/94f378b2-531d-4775-a230-e5f71f291e58.sized-1000x1000.JPG?",
       "stmt": "Hi I am your future Class Board President. As a first generation American and college student I have found myself appreciating what this country has to offer more and more every year. Spending most of my life between Princeton, NJ and Beirut, Lebanon has given me a priceless mix of cultures and understanding of the differences among people. Because of this, as Class President I would effectively be accurately representing first-gen, domestic and international students (A majority of the population at Penn). As President I would work on eliminating at Penn the bigotry and racism that exists in the country at the moment because there is no space for that here. Not only would progress be made on ensuring that the Penn campus is a haven for all people but mass peaceful counter-protests against hate groups that show up on campus would also be organized as a community project. Moreover, my platform simply is structured around the words fun and free. New and old popular initiatives that give students several FUN events and FREE things to make the 70 K sticker feel a little more worth it than it already is. "
     }, {
       "name": "Gideon Abramowitz",
       "photo": "https://snworksceo.imgix.net/dpn/735eec78-56b0-453b-95ae-44a622236ea5.sized-1000x1000.JPG?",
       "stmt": "GID will Get It Done. My fellow classmates, congratulations on making it to Furda’s A-List. The class of 2021 is an incredible group, bearing the best athletes, activists, musicians, and scholars from around the world. This is our time, and I want to lead you to make sure your journey at Penn starts out strong. With such a diverse and talented student body, I want to unite the class of ’21 to thrive collectively. I have many ideas for events to bring us all together and build connections, including an outing to a 76ers game (#TrustTheProcess) and a snowball fight in the Quad this winter. In addition, I want to share my passion for community service, and encourage the class to volunteer with organizations across Philadelphia. It would be an honor to serve as your President and bring our class to new heights. Remember, Get It Done with Gid. "
     }, {
       "name": "Jude Dartey",
       "photo": "https://snworksceo.imgix.net/dpn/ba70b35c-bcbf-4fd9-8e5e-e0bb97ae60fb.sized-1000x1000.JPG?",
       "stmt": "My role as President will be very simple: I will be an advocate for the Class of 2021. I am not a person who makes promises that I can’t keep, so I will use this medium to tell you a little bit about myself. I was born and raised in Ghana, West Africa. My family settled in America when I was 11. I spent the first few years in America figuring out how to fit in with others and I plan to use that experience to make our class inclusive to the point where everyone feels welcome. I am also a first generation, low income student. While some might argue that this comes at a disadvantage; I argue that my identity has taught me to use the most of the resources that are given to me. I do not put anything to waste. I am confident that I can use every ounce of every single resource available to me to fabricate your desires into existence. I am very aware that I cannot earn this position without the votes of the class so my first and only priority as President will be to serve as the voice behind your vision on how this class should be run. I recently walked into King’s Court English House dining hall to grab dinner with my best friend. His choice of dining is limited to King’s Court given that he keeps halal. After swiping his card, he was informed that no halal food was available for him that day. I saw the frustration in his eyes as he exited the dining hall having wasted a swipe. I  immediately understood his rage because he is paying for a dining plan but is not guaranteed a full meal everyday. This incident was my motivation to run for a position on the Undergraduate Assembly (UA). All great things in this world have their faults. My goal as a member of the UA will be to highlight these faults on campus and alter them to for the betterment of our campus community. Perfection does not exist on earth, but we can TRY to attain it within our campus one step at a time. That first step is to cast your vote for Jude Dartey."
     }, {
       "name": "Saachi Datta",
       "photo": "https://snworksceo.imgix.net/dpn/497f463d-db42-4ceb-b21b-b6fbe5731b06.sized-1000x1000.JPG?",
       "stmt": "Hey everyone! I’m Saachi Datta, a freshman in the College and would love to represent you as our Class Board President. I’m from Atlanta, and I came to Penn for the people. We’re spectacular, intelligent, diverse, and I am honored to be a part of our Class of 2021. Your health and happiness are close to my heart; so, as part of my presidency, I want to raise awareness about, and help combat, “Penn face.” An honest culture towards ourselves and our friends creates a culture that promotes good vibes, leading to successful lives. How do I plan on doing this? I want to run a positivity campaign, “Treat yourself” days, fun events like “Big Games, Small Food!” (think trashcan pong, gym-sized monopoly, etc. with finger sandwiches and other mini foods) and Around the World in 8 Days! Of course, alongside my other class board members I hope to be able to collaborate with them to plan great social events to help us get to know each other well, and I am always open for suggestions. If you see me walking around, let’s stop to chat, or even just say hi! And don’t forget…for a designer year: vote verSAACHI! "
     },{
       "name": "Luis Gomez",
       "photo": "https://snworksceo.imgix.net/dpn/d3bd5a14-37bb-46d6-aee9-3f66d88b454f.sized-1000x1000.JPG?",
       "stmt": "My main priority as class president would be to promote diversity and acceptance among our classmates and the Penn community at large. I aim to do this through a mixture of school and West Philadelphia oriented events which I would like to add to class board programming for each year. Some of the major events I would like to establish this year are an international potluck banquet hosted in Franklin Field Stadium, bi-weekly club spotlights, and the ‘West Philly Market’, where Penn students will be able to donate clothing, appliances, and art to be sold at discount prices to residents of West Philadelphia communities. Penn is far from perfect. I don’t believe that these events or the work I put into them will be able to fix its institutional and cultural problems. But what I do believe is that as your president I can help build the steps towards a more inclusive and more equal community."
     },{
       "name": "Summer Kapanka",
       "photo": "https://snworksceo.imgix.net/dpn/68b16329-c019-4850-9c99-b479dc526854.sized-1000x1000.JPG?",
       "stmt": "Hey y’all! It’s Summer Kapanka. You may know me from the ~infamous~ GroupMe, the Facebook page, etc., but now I’d like to know YOU as your Class President. The University of Pennsylvania Class of 2021 is filled with bright thinkers, out-of- the-box ideas, and diverse minds. As President, I hope to foster a community to connect YOUR ideas together (think power to the people). Instead of solely forcing my ideas on you, which include mini student run concerts and a Class of 2021 time capsule to open in 2071, I want to focus on what YOU want. I plan to send polls out to the grade to gauge interest in events, instead of wasting time and money on things that no one actually wants to go to. Also, I want to set up a survey for anyone who has ideas on what we should do as a class. This way we can get anonymous (or non-anonymous) suggestions from anyone and everyone. Much better than me just telling you what to do, right? If you have any questions, comments, or memes, feel free to shoot me a Facebook message. My “office” is always open ☼☼☼ And remember… It’s Always Summer in Philadelphia"
     }, {
       "name": "Tyler Kelly",
       "photo": "https://snworksceo.imgix.net/dpn/0dcb2655-5188-4595-84d7-f7dd978ab5e3.sized-1000x1000.JPG?",
       "stmt": "My name is Tyler Kelly, I am from Massachusetts, I am enrolled in the School of Nursing, and I want to be the Class of 2021 Class Board President.  One of the major components of being Class President is organizing the traditions that we have here at Penn, and in order to be an effective President, one has to be organized, focused, and outgoing. By voting for me for Class President, I can guarantee that I will efficiently carry out all necessary tasks in order to have a successful year. Personally, participating in volunteer work is a huge part of my life. Every summer, I volunteer at a summer camp that is designed for children affected by certain neuromuscular disorders, which entails the campers being in wheel chairs. I volunteer at this camp because being able to help others and make a difference in the lives of others is an integral part of my life. Transferring that ideology to Class President, making a difference in the lives of other students at Penn is extremely important to me, so voting for me is a vote to make a difference for all."
     }, {
       "name": "Moksh Jawa",
       "photo": "https://snworksceo.imgix.net/dpn/64fa8d72-0865-4834-bc7b-d3a8a438a015.sized-1000x1000.JPG?",
       "stmt": "Hey Class of 2021!<br>My name is Moksh Jawa and I’m excited to be running for Freshman Class Board President. Although my decision to attend Penn was last-minute, I haven’t regretted it for a moment because of the people and community I’ve found. Penn has quickly become my home but I want to make Penn our home. I plan to do that by organizing more than just social events - by planning events that will unify us for not only our 4 years at Penn, but also the many years after. I hope every day is an exciting one where we learn from, meet, and smile with some of the most phenomenal people we will ever meet.<br>I plan to have mini-NSO’s every year so we meet more people, amazing class gear giveaways, socials where we meet people from outside our academic school or dorms, and much more. Most importantly, I want all of you to have your voice heard so we can work together to make our freshman year the best possible. I truly believe the Class of 2021 is the best class at Penn yet and I’d love to lead our amazing class to the best year ever.<br>#MJAllTheWay"
     }, {
       "name": "Jonathan Roth",
       "photo": "https://snworksceo.imgix.net/dpn/e79dc4fc-e845-418c-9ab3-e23909e0c778.sized-1000x1000.JPG?",
       "stmt": "Leadership has played a fundamental role in my life for as long as I can remember. I have always been viewed as a gregarious and outgoing person, and I pride myself on being a voice for the people. Leadership can be expressed in multiple ways, and I try each day to embody as many different methods of leadership as possible. I am running for President of our great Class of 2021 because I want to ensure that our diverse range of talents and skills are implemented properly to bring change to our school, our community, and our world. I have experience as a leader, having served as Class President for my Freshman, Sophomore, and Junior years of high school, as well as Student Body President my Senior year. I know that our class is capable of achieving whatever goals we set out to accomplish, and I know that I can lead us to bring about that vehicle of change. I will bring experience, integrity, determination, and an open mind to our Class Board, and I cannot wait to be there as we discover our identity and our ability to change the world."
     }, {
       "name": "Anthony Scarpone-Lambert",
       "photo": "https://snworksceo.imgix.net/dpn/e07907a1-f7bf-4ddd-aac1-5efccb8b404b.sized-1000x1000.JPG?",
       "stmt": "“Are you the kid from the video?” It’s a question I get a lot. Whether walking down Locust, taking notes in class, or eating dinner at Hill, I’m never surprised when I hear from behind me, “Are you the kid from the video?” Yes, I am the kid from the video, but I am also Anthony Scarpone-Lambert, candidate for Class Board President. I am the kid who is on a mission to create a supportive, kind, passionate, spirited, and enthusiastic community within the Class of 2021. I am the kid who is on a mission to decrease Penn Face, host a “Week of Kindness”, boost our school spirit, and increase attendance to sporting and performing arts events. I am the kid who is on a mission to create “Pop-Up Events” throughout the year, lead a service project, spotlight students from the Class of 2021… the list goes on. If you have seen my Penn Acceptance Reaction video, you would know just how excited I am to be here, but it doesn’t stop there. My enthusiasm for Penn and our class shines every single day. Thank you, Class of 2021. For more information, please visit facebook.com/AnthonySLPresident2021"
     },{
       "name": "Robert Sim",
       "photo": "https://snworksceo.imgix.net/dpn/86fd84f6-55b5-45d3-9865-7f4a41f51d5c.sized-1000x1000.JPG?",
       "stmt": "I’m Robert Sim and I’m running for Class Board President. <br><br>As a first-generation student from Philadelphia, I am where I am today because of my community. At Penn, we all come from different socio-economic, geographic, and cultural backgrounds. I’ll listen to you, relentlessly fight for you, and serve you—regardless of which community you come from. <br><br>I want to not only improve our current events, but also implement my own ideas, such as allocating funds for more free giveaways and fun social events. Believing we should be more expressive of our pride, I hope to revive and rejuvenate our school spirit, especially during sporting competitions. From cultural festivals at a park to class barbecues at a lake, I want our class to embrace our diversity, to bond, and to be inclusive. <br><br>I want to initiate accessible outreach programs. From increasing financial aid to help people attend class-sponsored events to reaching out to less participative students, it’s ultimately my goal to unite our entire class together as a family. <br><br>Becoming the ears to your voices, I hope to be more representative of our entire class. Thus, I hope you’ll vote for the candidate you can always trust. The vote is SIMple. "
     },  {
       "name": "Lizzie Youshaei",
       "photo": "https://snworksceo.imgix.net/dpn/badea7d0-9508-488a-b05c-3a9a681e8569.sized-1000x1000.JPG?",
       "stmt": "Many of you know me as the girl with every vowel in her last name. Others know me as the Persian American Jew who took a gap year to volunteer in Bali. But enough about me. This election is about you. You deserve a candidate who will bring us together by throwing awesome events and create lasting memories. And I want to be that candidate. I want to listen to your opinions. But more importantly, your stories. We’re in college not to make friends with our textbooks but to make lifelong friendships with one another. Here are 3 ideas to get started: 1) NSOver Again, a weekend of events to welcome us back into second semester. 2) Food truck festivals before finals. 3) Intercultural events to celebrate the foods and music that represents our diverse class. And maybe even a sleepover in the Palestra, because what’s better than a night of snuggling and s'mores with 3,000 of your best friends? These events will turn our class into a family. I’m so thankful for all the wonderful people this experience has allowed me to meet and I’m excited to continue exchanging ideas and trading stories over the next four years. "
     },{
       "name": "Alex Xu",
       "photo": "https://snworksceo.imgix.net/dpn/7152e8e7-f9cc-4293-86d0-e31d2f1dd2b6.sized-1000x1000.JPG?",
       "stmt": "Hi! My name is Alex Xu and I’m running to be your Class of 2021 President. Over the past few weeks at Penn, I’ve been trying to meet and talk to everyone I’ve run across, and I’ve been deeply humbled and inspired by incredible group of students we have at Penn. I’m not running for fame or a good looking resume, but a genuine desire to serve our class. My roommate, Cal Williams (who’s running for Executive Vice President), and I have a lot of great ideas to promote class and school spirit, but what really sets us apart is our sincere commitment and interest in our class. I encourage you to say “Hi!” if you see me walking around campus, but I’ll probably get to you first. I’d love to share my ideas and convince you why I’d be a great fit for Class Board President. It would be a tremendous honor and privilege to represent our class on the Class Board. Let’s make our first year at Penn amazing."
     },{
       "name": "Zachary Zamore",
       "photo": "https://snworksceo.imgix.net/dpn/3d1c59f5-e13f-4a59-b594-eac3e8ac98be.sized-1000x1000.JPG?",
       "stmt": "If you want more, vote for Zach Zamore <br>1. More food: Weekly food tastings from some of the best restaurants in Phill <br>2. More apparel: Constant Penn apparel giveaways throughout the yea <br>3. More events: Increase the frequency of Class of 2021 events like concerts and a multicultural night with even more food showcasing the diversity of restaurants in Philadelphi <br>4. More fun: Study breaks every week to decrease the stress of students through events like movie trips and trips downtown."
     }
    ],
    "College_Chair" : [
      {
        "name": "Charles Curtis-Thomas",
        "photo": "https://snworksceo.imgix.net/dpn/497768f8-4f4d-4c9f-8ecd-e9e29c19685d.sized-1000x1000.JPG?",
        "stmt": "Hey everyone! My name is Charles Curtis-Thomas and I’m running for UA and College Class Chair. I’ve gotten to meet many of you over the past few weeks and share my ideas with you, and I know I made the right choice coming to Penn. 10, 20, even 30 years from now, I want to look back on the Class of 2021 as the greatest class in Penn’s history. I want our class to produce future economists, future nurses, future impactors, and future world changers. On the College side, I have noticed that there are many intra-school activities that involve the other three schools, but not many specifically for the College, which has the largest collection of students. I intend to change this, and create fun activities for College students. Finally, I plan to fix problems around our campus, such as implementing central cleaning stations to deal with bugs, implementing more water filling stations, finally putting accessible trash cans around the Quad and other college houses, and more. I’m excited to work with you to help improve our already impressive community. If you want Penn to be the best it can be, express your right and vote for CCT."
      },{
        "name": "Chioma Duru",
        "photo": "https://snworksceo.imgix.net/dpn/1dd064a3-fb01-4a79-9300-be252a6ac724.sized-1000x1000.JPG?",
        "stmt": "Hey! My name is Chioma Duru. If we’ve crossed paths, you may also know me as “Chi-Chi-Chioma.” But for those of you who don’t, I'm excited to get to know you. Here’s some background about me. I’m from Houston, TX, I’m a Nigerian-American female and go by she/her/hers pronouns. I’m extremely passionate about meeting new individuals, bringing the energy, and putting smiles on people’s faces. I’m always looking for new ways to bring different groups of people together and always want to make those around me feel welcomed.This means learning more about different cultures and embracing the differences that make us so unique. I hope to continue doing this as a member of the class board, serving as your college chair. In addition, I’m open to new ideas, social issues and love discussion. So feel free to come up to me whenever. With your help, I hope that we can create a stronger sense of class unity and school spirit.<br><br>Besides, there’s always growth with Chi-Chi-Chioma!<br><br>#VoteMeVoteChi"
      },{
        "name": "Daniel Gordon",
        "photo": "https://s3.amazonaws.com/media.dpn/51345_fillerimgf.jpg",
        "stmt": "My name is Daniel Gordon and I am running for College Chair for the Class of 2021. It has been my absolute pleasure to talk to many of you and I am excited to meet the rest of C’21 over the course of the next four years. On the Class Board, I would work to increase school spirit, bring students together, and to maintain Penn’s traditions. In addition to keeping the Harry Potter long sleeve t-shirts (CAS is Gryffindor!), it is important to have CAS-wide events to bring students across the Class of 2021 together. This includes an expansion of College Palooza into the fall and Major Mixers so students can find friends with similar interests. I would also facilitate the Econ Scream tradition events during Spring Fling as opportunities for college students to destress and institute pop-up events where students receive free food and spirit wear. If you have any suggestions, or would like to influence the class board, feel free to reach out to me at dagord@sas.upenn.edu. I’m excited to share a wonderful year with you all. "
      }, {
        "name": "Juan Lopez Salazar",
        "photo": "https://snworksceo.imgix.net/dpn/7574478a-569d-46a6-b057-0f2de9f6fa68.sized-1000x1000.JPG?",
        "stmt": "Renowned philosophe and poet, Quavius Keyate Marshall, more commonly known as Huncho Houdini and Quavo Ratoutille, once uttered this resounding statement, “Do it for the culture [or] they gone bite like vultures.” Whether he was alluding to Wharton undergrad students preying on their struggling classmates or the death of culture, Mr. Marshall’s statement still gives me hope that the demise of culture will never see the light of day. I ask of you to look around before you continue reading: Do you hear people speaking different languages? Do you see people wearing different religious hallmarks? Do you feel surrounded by cultures? I am trying to take that last feeling and weave it into each thread that makes up our class of 2021 t-shirts. I want culture to be heard from La Casa Latina in Arch to the football stands at Franklin Field. I hope you want culture to exude out of every member of the class of 2021. Allow me, Juancho Houdini, like Quavius, to do it for the culture so no vulture can be spotted in the “Year of Innovation.” Let’s innovate, generate, and appreciate culture on campus by making me the College Chair for the class of 2021. "
      },{
        "name": "Vanessa Lundstrom-Placencia",
        "photo": "https://snworksceo.imgix.net/dpn/ca8a1dac-c9a0-408e-a993-5c57ebbf522c.sized-1000x1000.JPG?",
        "stmt": "Hi, I’m Vanessa Lundstrom-PLacencia! Thank you for considering me to be your next representative. Representing the student body is not a role to be taken lightly and each and every one of the decisions made on my behalf will be centered on the best interest of my classmates, the University of Pennsylvania Class of 2021. My closest friends would describe me as an effective communicator and leader who is not afraid to get my hands dirty. I am ready to voice both your proposals and concerns. Come share your ideas and I will make them happen. PSA: There is no ‘L’ in Vanessa, so go for the ‘W’ and vote for VANESSA!!!!"
      },{
        "name": "Eric Zhao",
        "photo": "https://snworksceo.imgix.net/dpn/d9da23c3-b4d5-4c10-8f8f-c930dfb16650.sized-1000x1000.JPG",
        "stmt": "Hi I am your future Class Board President. As a first generation American and college student I have found myself appreciating what this country has to offer more and more every year. Spending most of my life between Princeton, NJ and Beirut, Lebanon has given me a priceless mix of cultures and understanding of the differences among people. Because of this, as Class President I would effectively be accurately representing first-gen, domestic and international students (A majority of the population at Penn). As President I would work on eliminating at Penn the bigotry and racism that exists in the country at the moment because there is no space for that here. Not only would progress be made on ensuring that the Penn campus is a haven for all people but mass peaceful counter-protests against hate groups that show up on campus would also be organized as a community project. Moreover, my platform simply is structured around the words fun and free. New and old popular initiatives that give students several FUN events and FREE things to make the 70 K sticker feel a little more worth it than it already is. "
      }
    ],
    "Engineering_Chair" : [
      {
        "name": "Sheila Gaur",
        "photo": "https://snworksceo.imgix.net/dpn/f005fe63-7d13-49e4-bb4b-0c18ef3bd807.sized-1000x1000.JPG?",
        "stmt": "Hi, my name is Sheila Gaur and I would love to serve as your Engineering chair. My main goals are to unite the engineering class and to make administration prioritize our interests and issues. As a dual-degree student in Wharton, I have seen how much emphasis Wharton puts on student unity through the cohort system and numerous other activities. Engineers should have these same resources and opportunities—I am passionate about strengthening our community through engineering events such as meals at local restaurants (Distrito, Thai Shanghai, the possibilities are endless) to ensure that the people we meet are not just inside Towne and DRL. By bringing our class together, we can ensure that Engineering students are an active voice in the university (how about some merch in the bookstore?) and that our issues become the university’s top priority. Since I have served in student government before, I feel comfortable in representing you, the Engineering students of Penn, and making sure that your needs are addressed. Thank you for your support, and I look forward to improving your Penn experience!"
      },{
        "name": "Nick Genovese",
        "photo": "https://snworksceo.imgix.net/dpn/37142b73-6e12-4119-b954-be86e74161b4.sized-1000x1000.JPG?",
        "stmt": "Hello, Penn Engineering Class of 2017!! My name is Nick Genovese, and I would like to represent you as the Class of 2021 Engineering Class Chair. If elected, my goal is to integrate the engineering community with the current Penn traditions we see on campus, to give all engineering students a more impactful way to represent themselves in the Penn community. Engineering students are always looked to as the “math and science” kids, with the most intense workload and the least amount of free time, yet it is just as important for us to be represented in the social aspects of life at Penn. The Engineering community here at Penn has so much to offer, and participating in these traditions will allow for this to be showcased throughout Penn. By adding an engineering aspect to current traditions, such as a float building competition and parade at homecoming, and adding more social events strictly for Penn Engineers, we can bridge the gap between the Engineers at Penn, and the rest of Penn as a whole. My priority is to make this freshman experience both social, and enjoyable for all “Penngineers”. Thank you for your time, and remember to vote for Nick!!!"
      },{
        "name": "Rachel Madhogarhia",
        "photo": "https://snworksceo.imgix.net/dpn/928f0447-ce53-4587-9bec-e494e1d9e15d.sized-1000x1000.JPG?",
        "stmt": "Hello! My name is Rachel, and I am running for your SEAS Class Chair for Class Board 2021. I’m from Los Angeles, California, and I went to Harvard-Westlake High School, where I was on the Yearbook Staff and Golf team. I am majoring in Bioengineering/Biomedical Applied Science, and I’m also interested in an English or Bioethics Minor.<br><br>I am so excited to run for your Engineering chair! Although I’ve only been at Penn a few weeks, I love our class and cannot wait to start organizing events for it. As part of class board, I hope to ensure that the interests of SEAS are represented in all events we plan. More importantly, I am big on a strong community, so I will always support fun events that give SEAS students a chance to get to know not only one another, but also other students across all schools and programs. I would love to take ideas for any kind of event or project, whether it be something that builds on previous traditions or something new and out-of-the-box. Additionally, I will put my best effort towards spending as much of my time as I can working on Class Board."
      },{
        "name": "Sanjana Rao",
        "photo": "https://snworksceo.imgix.net/dpn/fd708610-1784-41de-ae5d-0e00ea374ba8.sized-1000x1000.JPG?",
        "stmt": "Hey! My name is Sanjana Rao and I’d like to be your 2021 Engineering Class Chair! I’m from central New Jersey and I’m likely going to be pursuing a Chemical and Biomolecular degree from the School of Engineering. Outside of class, I’m a passionate visual artist and designer, so I’m considering a minor in Digital Media Design as well. As your Engineering Class Chair, I will be representing the School of Engineering in the Class Board. In addition to putting my time towards Penn’s traditional events such as Feb Club and Hey Day, I will also help organize smaller and more frequent events including study breaks events near finals and fun evening events to help de-stress from the heavy engineering workload. As the architects of innovation, we, in the School of Engineering, strive to craft efficient and ergonomic technologies in our different branches; for this reason, I want SEAS, through the Class Board, to get more involved in service and outreach projects. Lastly, I want to promote interdisciplinary and cross-sectional education within the School of Engineering, cultivating peculiar and distinctive perspectives found at the crux of science and arts. Thank you and I encourage you to SEAS the day by allowing me to SEAS your vote!"
      },{
        "name": "Alexa Spagnola",
        "photo": "https://snworksceo.imgix.net/dpn/2362532b-1fd8-4f60-a175-66f2c791a958.sized-1000x1000.JPG?",
        "stmt": "My name is Alexa Spagnola and I’m running to be the 2021 Engineering Class Chair. As a part of the Electrical and Systems Department, I couldn’t help but break my platform down to mirror an RC Circuit: Representation, Community, and Connection.<br>I will ensure that engineering students know that they deserve to be here.  The term “imposter syndrome” has become too prevalent within SEAS. Having witnessed firsthand how programs such as Advancing Women in Engineering combat both insecurities and prejudices, I aim to implement similar strategies for the Representation of all demographics.<br>Having experience representing engineering interests at the 2017 Conference on National Affairs and as an applied physicist at NASA, I understand how our Community fits within the greater scope of the world. As a member of the Class Board, I would be tasked with ensuring that our voices are not ignored, and it is a task I am certainly up for.<br>Too often within SEAS I have overheard that engineers feel isolated by a hefty courseload, and as Chair I would organize schoolwide events to Connect the various departments, such as socials and lunches. I hope that I earn the honor of being your Chair. Thanks!"
      }
    ],
    "Wharton_Chair" : [
      {
        "name": "Evan Batov",
        "photo": "https://snworksceo.imgix.net/dpn/9c9b60e3-9ab7-4848-adb1-8c20237c25d2.sized-1000x1000.JPG?",
        "stmt": "Fellow Whartonites and Penn students! My name is Evan Batov and I am running for Wharton Class Chair this election. Although I have only stepped on campus barely a few weeks ago just like all of you, I already know for sure that my Penn journey would be incomplete without some line of service. Wharton is a place of the greatest innovators, thinkers and scholars from all walks of life. That’s why we need the ideal candidate for this job. I’ve had the honor to meet many of you during NSO and the past few weeks, as well as hear some of your cries and woes: the ambiguity of Wharton 101, getting lost in Huntsman, and the list goes on. But in all seriousness, I plan to work with the administration to address some of the concerns all Wharton students face. Personally, I come from a background where I looked forward to studying many distinct areas and interests, as well as break boundaries. With that mind, I hope to create and sustain a network where we can all depend on one another, share our many passions outside of our concentrations, and learn about the differences that make us up. Our community is the most important asset we have - not stocks or bonds, believe it or not - and I want to represent it and listen to it in the best way possible. So take my hand, vote for me and let’s break boundaries together. No more nonsense, only forward. Evan Batov for Wharton Class Chair!"
      },{
        "name": "Jose Mendoza",
        "photo": "https://snworksceo.imgix.net/dpn/4889a8e1-62f4-4f10-a744-3b6c9b8af37d.sized-1000x1000.JPG?",
        "stmt": "Now I know what y’all are thinking, another snake is running to represent us, the monolith that is the Zoo…or Wharton (Interchangeable? Yes. Debatable? I wish).  But truly all jokes aside I, Jose Mendoza, am running for the opportunity to represent us for Wharton Chair because I believe in a school that is just and fairly represented among all our other peers. Coming from the good ol’ Lone Star State I’ve learned a few things, Texas is hot, Whataburger is amazing, and we can cook some darn good BBQ. Now what does that have to do with being Wharton Chair, you ask? Absolutely nothing, but I can assure y’all one thing. If I’m elected I’ll do everything in my power to not only rightfully represent us, but create amazing opportunities that can help expose us to see more of this world whether that’s through organizing trips, or bringing business people to speak to our class. I guess if anything what I said earlier does reiterate a very important factor. The fact that we’re all so different-bringing our perspectives from all over world, but still band together because we,   We believe in school that sssstands up for what is right.  Go Snakes, oh crap, I mean Wharton! Sincerely, Jose (That Mexican kid with that really common Mexican name)"
      },{
        "name": "Jay Mudholkar",
        "photo": "https://snworksceo.imgix.net/dpn/9f70cdf3-8ef8-4c50-97ad-9e43d735a353.sized-1000x1000.JPG?",
        "stmt": "Hello Wharton Class of 2021! My name is Jay Mudholkar, and I would like to be your Wharton Chair (hiss). Class Board is a nice way for representatives from different schools with different roles to come together and create solid events that help our class mesh. The reason I’m running for Wharton Chair specifically is because I want to better integrate Wharton students in those events and promote the positives Wharton students bring to make Penn more fun. It’s easy to single out Wharton kids as sneks with no passion, but we really do bring some pretty cool talent to Penn: let’s let that thrive at Econ Scream, at Fling, at NSOver again, at all the dope events Class Board throws.. Vote Jay for Wharton Chair!! #Jliketheletter"
      }, {
        "name": "Sam Oshay",
        "photo": "https://snworksceo.imgix.net/dpn/b30ded06-9eb2-43ac-b57b-ddfcc8eae79b.sized-1000x1000.JPG?",
        "stmt": "Dear Baby Snakes:<br><br>As of now, the plurality of Wharton students go into finance and consulting upon graduation. These are noble and necessary professions, yet I believe these fields draw so many Whartonites because they are simply an extension of our time at Wharton: structured and prestigious. While many of these students are in love with what they do, I think that just as many are there because they have not yet found their shtick. I want to join the Class Board to advocate greater focus on alternate careers paths, such as entrepreneurship and public policy, and to ensure that fewer students leave the school without finding “it.”<br><br>In addition, if you have met me, you know that everything I do is over the top. Based on this fact alone, you should vote for me because the events I will plan as Wharton Class Chair will be equally over the top; they will be your epic, unforgettable memories of freshman year that you can look back on for years to come. So, baby snakes, Vote Oshay!"
      },     {
        "name": "Cameron Rhind",
        "photo": "https://snworksceo.imgix.net/dpn/adc78ddc-23f4-4073-b500-7d3225bc9ddb.sized-1000x1000.JPG?",
        "stmt": "Hello everyone! I hope you’ve had a great first few weeks at Penn and specifically at Wharton so far. My name is Cameron Rhind and I am thrilled to be running for Wharton Class Chair. I am from New Canaan, Connecticut and am planning on concentrating in Finance and Statistics. I look forward to bringing a ton of school spirit to Wharton and the rest of Penn. As captain of the swimming and diving team on high school, I learned how to bring a diverse group of peers together. At Penn, I hope to raise Quaker spirit inside and out of the pool! If you have any ideas on how to enhance your Wharton experience or just want to say hi, please come introduce yourself! It’s going to be a great year filled with spirit, passion, and excitement! Vote Cameron Rhind, on the grind!"
      }, {
        "name": "Sarah Rogers",
        "photo": "https://snworksceo.imgix.net/dpn/d0abdd77-ed85-4347-884a-c37204926428.sized-1000x1000.JPG?",
        "stmt": "Hey Wharton Class of 2021! I am so excited to be running for Wharton Chair— I am a fun, determined, outgoing and an overall vivacious girl hailing from Jersey ready to take this year by storm! I plan on doing so many fun things freshman year with our class and cannot wait for the opportunities awaiting all of us here. I will channel all my school spirit into making events that people ACTUALLY want to go to. I’m a very approachable person so feel free to come up & introduce yourself!<br><br>Need something? Roger That! ;)"
      }
    ],
    "Nursing_Chair" : [
      {
      "name": "Anjelique Agudo",
      "photo": "https://snworksceo.imgix.net/dpn/10e16eb8-63eb-4cd2-85a7-dc3925a4f6fb.sized-1000x1000.JPG?",
      "stmt": "Hey Penn Nursing Class of 2021!<br><br>My name is Anjelique Agudo, and it would be an absolute honor for me to serve as your nursing class chair this school year! As prospective nurses, we are all learning the values of love, commitment, responsibility, and compassion. My goal is to use these values to represent our class this school year. I believe that I am a good representative for the Nursing Class of 2021 because I am wholeheartedly committed to giving you a memorable freshmen year. As a self-motivated leader, I would not only like to influence the lives of my fellow students, but I would also like to leave an everlasting mark of unity on our campus. Through my actions, I hope to bring positivity among the student body. I want to be a voice for the nursing students by attending to all of your concerns. More importantly, I plan to value the opinions and thoughts that each and every one of you have. If given the chance, I promise to serve you and be there for you along every step of your freshmen year. <br><br>Thank you!<br><br>VOTE ANJELIQUE FOR NURSING CLASS CHAIR!"
      },       {
      "name": "Shanaya Cross",
      "photo": "https://snworksceo.imgix.net/dpn/321e2db2-ae9b-480d-b915-8a93487cb933.sized-1000x1000.JPG?",
      "stmt": "Hi! My name is Shanaya Cross (I sometimes go by Shay) and I am running for the Nursing Chair for Class Board 2021! It would be such a privilege to uphold Penn traditions as a part of Class Board, and it would be an even greater privilege to voice any awesome event ideas our nursing cohort has! If I am elected to Class Board, every nursing student in our cohort will have a say in the event planning that Class Board conducts. Our class size makes it easy for us to communicate with each other and, if elected, I plan on using our GroupMe and our Facebook page to gather your thoughts and ideas so that we are most accurately represented. I would love to collaborate with other classes and other schools for events as I believe such to be beneficial for the School of Nursing as well as the entire University. I can only hope to represent such an amazing group of people on Class Board! Vote Shanaya Cross for Class Board 2021 Nursing Chair! "
      },{
        "name": "Tommy Seaman",
        "photo": "https://snworksceo.imgix.net/dpn/f25ca05b-cc3b-499b-b469-455ae4efacdf.sized-1000x1000.JPG?",
        "stmt": " Hey everyone! My name is Tommy Seaman and I grew up 3,000 miles away in a small town near San Francisco called Los Gatos. Coming from a small area where I became involved in student government in my high school and at the local level, Penn brings a whole new set of opportunities and challenges that I am excited to face. What we are all going through right now as freshman is a little bit like walking into a doctor’s office- disillusioned, confused, not quite sure what’s going on. While your mentors and faculty act as your doctors, explaining what you’re feeling and offering treatment and guidance, allow me to (fittingly) act as your nurse. Just as a nurse would, I will advocate on your behalf, acting as a middleman between the nursing class and the Penn community. As the Nursing Chair for the Class of 2021, I will make sure that the small yet mighty nursing class has a voice on campus. I will assist the nursing class in establishing an influential presence on campus and within the student body. I plan to serve Penn in the best way possible and I hope to have your vote! "
      },{
        "name": "Sophia Schulz-Rusnacko",
        "photo": "https://snworksceo.imgix.net/dpn/2b18d7ae-10f7-47b8-a85d-d1923b0fd457.sized-1000x1000.JPG?",
        "stmt": "Hi! My name is Sophia Schulz-Rusnacko and I’m a freshman from Minneapolis, Minnesota. As Class of 2021’s Nursing Chair, I want to serve a liaison between the School of Nursing and the other three undergraduate schools. Nursing is sometimes overlooked or forgotten about because we are so small, so I want to bridge the gap between schools while also educating non-nurses about what we do! In Nursing 101, we’re learning about the stigma and stereotypes surrounding nursing, and as Class Chair, I would love to educate the entire Penn population about nursing’s REAL role in healthcare and society."
      }
    ],
    "Executive_Vice_President" : [
      {
        "name": "Maher Abdel Samad",
        "photo": "https://snworksceo.imgix.net/dpn/39714908-e6cc-4970-846b-2b26662ff55d.sized-1000x1000.JPG?",
        "stmt": "I'm running for Executive VP of Class Board because every day I wake up in my tiny dorm room in Riepe, look around Penn and Think “damn, I’d TAP that”. By that I mean, I want to Thrive At Penn but most importantly, I want to see others Thrive. I think the best way to do that is by making people happy, closer together and closer to the fundamental traditions that underlie Penn. My platform is simple but intricate: it consists of three big ideas that are all interconnected. Inclusion, Expansion, Collaboration. By Inclusion I mean catering to the hundreds of ethnicities and nationalities at Penn as many students feel left out at times during Penn traditions and events. How will we do that? Expansion: adding events to NSO and expanding on current Penn traditions to make them Bigger and Better. Another Part of Inclusion is Socio-Economic Inclusion: Find ways to pay for many events such as fling tanks and Harry Potter Shirts. How? Collaboration with different groups and organizations on campus such as the UA and Student Financial Services. I have also many other ideas (like study breaks with Dogs/Cats) which you will hear about throughout the Campaign!"
      },{
        "name": "Sheryl Chen",
        "photo": "https://snworksceo.imgix.net/dpn/6bd1f5f5-ad6b-46fc-b6ba-9a1cb7c3dffc.sized-1000x1000.JPG?",
        "stmt": "Hey Quakers! I’m Sheryl and I am running for Executive Vice President of Class Board 2021. I hail from NYC, but I’m so excited to make Philly my new home. While Penn is an amazing place to learn, live, and grow, it can still be ten times more spirited. Class Board will give you all the ultimate student experience. Bonding events I propose include retreats to the Poconos, Paintball, Dodgeball and Basketball Tournaments, 5K runs, Family Feud and Jeopardy-style events. I hope that the Class Board will work closely with SPEC to make Spring Fling bigger and better this year. Furthermore, I would love to create more holiday-themed events. During Christmas time, there can be Secret-Santa exchanges with students from each college house and a week long of giveaways. During Valentine’s Day, students can fill out an online questionnaire to find potential matches. When the weather gets nicer in springtime, we can have free popsicle and lemonade stands and free personal hygiene/condom stands in the Quad and outside freshman dorms. Finally, I want more social events in casual settings, such as BYOs and bar crawls. I have past experience in planning fun events, and feel comfortable voicing my opinion - one which will represent this amazing class. Class of 2021, vote SChen for Penn!"
      }, {
        "name": "Louis Galarowicz",
        "photo": "https://snworksceo.imgix.net/dpn/e184a584-30f8-448f-bae1-2901b67613dc.sized-1000x1000.JPG?",
        "stmt": "Hi, my name is Louis Galarowicz, and I hope to represent YOU as vice president of our class.  I am a history/philosophy major in the College of Arts and Science, with aspirations of attending law school. Having been a leader on student council, debate team, SADD, and the track team, my experience with organizing and running events is all-encompassing and well suited for a position on Student Board. I am running to bring more Accessibility and Efficiency into the Penn experience. Our campus is abounding with great resources, but there are too many doors, both physical and metaphorical, closed to freshmen students. During the last few weeks, I have wasted considerable amounts of time walking to find open facilities. All too often, I find our dining halls and gyms closed, and our work areas locked or requiring reservation. As Ben Franklin quipped, “Time is money,” and my time is wasted by the lack of access we have to our resources. As Executive Vice President, I hope to save YOU, my constituents, time and money by keeping facilities open longer and cutting out the tiresome bureaucratic processes of campus life. For Accessibility and Efficiency, vote Louis Galarowicz for Executive VP."
      },{
        "name": "Jesse Liu",
        "photo": "https://snworksceo.imgix.net/dpn/912ce6ec-c20a-4518-a119-d008df368179.sized-1000x1000.JPG?",
        "stmt": "Hello, I’m Jesse Liu and I am running to be your Freshmen Class Executive Vice-President! I am originally from Rolla, Missouri and I want to try my best to ensure that your freshmen class experience here at Penn is fulfilling and fun, in and out of the classroom. I will work to not only try and serve as a voice to represent your interests on the class board, but I will work to promote class participation in the class board and in student government as a whole. We all worked hard to get here and we all deserve a voice in how the school is run! If elected, I will advocate for the creation of a platform where any freshmen can write suggestions to the class board for events and activities that other freshmen want to be a part of and I will also push for the addition of more options for dining dollars and swipes on campus, while also working with my peers on the class board to try and make more freshmen events. Let’s come together and create change on this campus. Remember, if you want a good voice for you, vote Jesse Liu! "
      },{
        "name": "Jackfille Pierre",
        "photo": "https://snworksceo.imgix.net/dpn/738bd81d-23db-4120-93bd-e45ed68b797e.sized-1000x1000.JPG?",
        "stmt": "How many promises have you had broken? How many plans have candidates deserted once elected? Are you tired of being misled? Same. My name is Jackfille (Jack-feel) Pierre and I want to be your next Class of 2021 Executive Vice President. My campaign will not be run on empty promises, I have exciting ideas and plans to set them in motion. My three main objectives are to increase school spirit, facilitate more class social events, and enable clear communication between the 2021 Class Board and the members of the class. To increase school spirit, I want to start by promoting sports culture among our class with events like Freshman Football day, where all the freshman would attend one football game together and sit in the same section. Activities would include pre-game tailgating and a face painting station. I also want to establish a Class of 2021 Spirit Squad that would attend different sporting events, as well as arts performances and plays. My other ideas include Movie Night on College Green, an end of midterms celebration in Houston, Pool Party at Pottruck, and a Google forms suggestion box. Come talk to me at the Midnight Breakfast to learn more. Let’s get real, Vote for Jackfille! #GetRealWithJackfille "
      }, {
        "name": "Cal Williams",
        "photo": "https://snworksceo.imgix.net/dpn/f90a0cae-81c0-40a2-b852-a1040fe675f5.sized-1000x1000.JPG?",
        "stmt": "My name is Cal Williams and I am running for the position of Executive Vice President for the class of 2021. When my roommate, Alex Xu, and I arrived at UPenn, we both had the same goal – to meet as many people as we could. Before we had even learned about the student government at Penn, we wanted to grow the school spirit in our class. By always keeping an upbeat mood and saying hey to everyone we came across, we hoped to make people feel more comfortable about being freshman at such a large school. When Alex and I heard that there were student government elections, we immediately signed up. With every one of us being new to Penn, it is imperative to instill a sense of school spirit and pride from day one. This will carry into our next three years and for decades to come. As silly as it may seem, whom you vote for now may influence the tone and reputation of our class forever. Vote for Cal Williams to represent the class of 2021 as your Executive Vice President!"
      },{
        "name": "Victoria Wu",
        "photo": "https://snworksceo.imgix.net/dpn/96e7dc90-1a4d-4bf1-a6b6-5bcc5a6a6673.sized-1000x1000.JPG?",
        "stmt": "Hey Class of 2021! My name is Victoria Wu and I would like to be your Class Board Executive Vice President. The decision to attend college is a big time-commitment as well as a huge financial decision. We all know Penn costs a fortune. But we all decided to come here because we believed that it was worth the cost. Spanning all fifty states and over ninety-four countries, we have the opportunity to learn and meet new people of all different backgrounds and cultures. While we work hard in our academics, we’ll need study breaks along the way! I hope to provide a wide variety of social activities for the student body to bring everyone together and make our huge campus feel like a close-knit community.<br>Vote for VWu for VP!"
      }
    ],
    "Vice_president_of_Internal_Affairs" : [
      {
        "name": "Sophia Kim",
        "photo": "https://snworksceo.imgix.net/dpn/94450873-f771-4909-90b7-7e3bc06dc2c4.sized-1000x1000.JPG?",
        "stmt": "Hi! My name is Seung Yeon Kim. Most people call me Sophia. But you can call (and VOTE for) me tonight ;)<br><br>I’m from a small city near Detroit, Michigan, where my high school didn’t have a proper student government. Nonetheless, from being President of a music-based community service organization to serving as the youth chair of a national Korean-American association, I discovered new meanings of leadership.<br><br>Now, as your VP of Internal Affairs, I will effectively collaborate with the other board members in order to organize unforgettable events for the Class of 2021. I am ready to put forth all my efforts in coordinating our class’s activities, and listening to all of your unique ideas as well. One idea that I hope to implement immediately is providing easier access to care packages that the Student Health Services provides by having stations in the dining halls/around the dorms (fight freshman flu)! <br><br>I’ve had a great time at Penn so far, and I can’t wait to meet all of you! Feel free to reach out to me on Facebook (look out for my campaign page for details on my platform!) or email me at sophskim@sas.upenn.edu."
      },{
        "name": "Daniel Wittmer",
        "photo": "https://snworksceo.imgix.net/dpn/910786a3-ed75-438a-b4fc-0e47421910ec.sized-1000x1000.JPG?",
        "stmt": "I want to be your Vice President of Internal Affairs pure and simple, and I’ll tell you why. I come from a small rural town in Kentucky where I grew up on a farm performing the stereotypical farming practices. Hoeing the garden, feedin' the cattle you name it. With this upbringing, southern hospitality and attentive listening are traits that I’ve acquired. I want to be an outlet for every single one of you, by truly hearing your ideas. As VP of Internal Affairs, my main duty is to set agendas for and plan board meetings. That's why I want to develop an online open discussion platform for the class of 2021 to write ideas and have peers vote on the significance of the idea. I can then take these important issues and make them the top priority at our board meetings for discussion. I came to Penn to learn about people from every background imaginable, so if you have any questions for me my campaign Instagram is bigD4VP. You can add me on all of my social media outlets from there! Thank you, God Bless, and vote Big Dan for Internal Affairs VP. "
      }
    ],
    "Vice_president_of_Finances" : [
      {
        "name": "Jai Ashar",
        "photo": "https://snworksceo.imgix.net/dpn/b03a5fa0-212b-4ed7-961e-21c58892f49d.sized-1000x1000.JPG?",
        "stmt": "Penn is much more than an Ivy League institution. What makes Penn unique are the traditions and events created by student government. I strongly believe that improving them and starting more will encourage pride, unity, and spirit among Penn students. One way I plan to do so is with an NSO part 2 in the beginning of the next semester, a Penn end of the year BBQ, and more activities that help provide a break from the stressful environment that us Penn students face. I will also work to make Penn swag more affordable in order to inspire more Penn pride. Philadelphia's sports teams are on the rise this year, so I hope to host school sponsored game nights with free food and merch. As VP of Finance I aim to focus school expenditures on transforming Penn’s campus to a place students can truly consider their home. I am confident I am the right candidate for this job; I will always give my best to make a difference for the causes I feel passionate about. For me, student government is the most crucial part of Penn, as it is the driving force behind the Penn family. "
      },{
        "name": "Sahitya Mandalapu",
        "photo": "https://snworksceo.imgix.net/dpn/ddc1e793-e1cb-4c00-a2c3-8eb4bac5d995.sized-1000x1000.JPG?",
        "stmt": "Hi everyone! My name is Sahitya Mandalapu, but call me Sith! I’m running for Vice President of Finances and the Undergraduate Assembly. I’m from Bethlehem, PA and I’m in Wharton studying Finance and Public Policy. As class president of my high school, I absolutely loved planning events for my peers. After planning homecomings, formals, and even a 12-hour dance marathon, I loved seeing the smiles of my peers and watching them come together as a class. If you have ideas for awesome events besides the traditions (like Econ Scream, Hey Day, etc.), I would love to hear them and present them to the rest of the Class Board. I really want to be our VP of Finances to continue my passion for social and event planning and connecting with my classmates. And as I study Finance, I think I will be great at managing our class’ spending and fundraising. I love meeting people so I urge you to say hi and introduce yourself if you see me! I want to be your VP of Finances, your friend, and your voice!! I stand behind my class and hopefully you’re with me too #ImWithSith "
      }
    ],
    "Vice_president_of_External_Affairs" : [
      {
       "name": "Danny Acosta",
       "photo": "https://snworksceo.imgix.net/dpn/7b5508a7-9f32-48bf-acf5-63ed0ed08648.sized-1000x1000.JPG?",
       "stmt": "Let’s keep our reputation of being the social ivy! Together we will continue Penn’s finest traditions like Hey Day, work with some newer events like 12 Days of Giveaways, and establish our own Class of 2021 events and festivals that will become traditions for future classes. I hope to heighten our school spirit and create a sense of unity and friendship throughout our entire class through 2021 exclusive activities. We’ll save on some meal swipes with lots of free food events and maybe even make Insomnia Cookies accept Dining Dollars. So, what do you say, Quakers?"
      },{
        "name": "Julie Chen",
        "photo": "https://snworksceo.imgix.net/dpn/f35f59f5-49a3-4d9e-b5a9-68f97a18a7ec.sized-1000x1000.JPG?",
        "stmt": "After three weeks of meeting hundreds of classmates, learning the Greek alphabet, and selfieing with Joe Biden, we, the Class of 2021, have finally settled in at Penn. If elected, my goal as Vice President of External Affairs will be to partner with outside organizations to bring our class together.<br><br>In the wake of NSO (and free food on every corner), we’re all getting tired of going to Hill every day for the same Mongolian Grill and scrambled eggs. As VP of External Affairs, I vow to partner with local food businesses in Philly to bring pop-up food events and snacks to campus.<br><br>To alleviate the academic pressure at Penn, I promise to plan study breaks and prioritize our mental health. For the annual Econ scream in the Quad, I will partner with donut, ice cream, and snack shops to celebrate before the clock strikes 12. In the middle of the semester, when midterms are piling on, I vow to plan numerous study breaks in partnership with Philly animal shelters, Zumba instructors, and coffee shops.<br><br>And as we spend these next four years together, I hope to make an impact on this campus I now call home. "
      }
    ]
  },
  "ua" : {
    "New_Student_representative" : [
      {
        "name": "Maher Abdel Samad",
        "photo": "https://snworksceo.imgix.net/dpn/39714908-e6cc-4970-846b-2b26662ff55d.sized-1000x1000.JPG?",
        "stmt": "I'm running for Executive VP of Class Board because every day I wake up in my tiny dorm room in Riepe, look around Penn and Think “damn, I’d TAP that”. By that I mean, I want to Thrive At Penn but most importantly, I want to see others Thrive. I think the best way to do that is by making people happy, closer together and closer to the fundamental traditions that underlie Penn. My platform is simple but intricate: it consists of three big ideas that are all interconnected. Inclusion, Expansion, Collaboration. By Inclusion I mean catering to the hundreds of ethnicities and nationalities at Penn as many students feel left out at times during Penn traditions and events. How will we do that? Expansion: adding events to NSO and expanding on current Penn traditions to make them Bigger and Better. Another Part of Inclusion is Socio-Economic Inclusion: Find ways to pay for many events such as fling tanks and Harry Potter Shirts. How? Collaboration with different groups and organizations on campus such as the UA and Student Financial Services. I have also many other ideas (like study breaks with Dogs/Cats) which you will hear about throughout the Campaign!"
      },{
        "name": "Sravya Alla",
        "photo": "https://snworksceo.imgix.net/dpn/77fd4e9e-88e1-4508-aea4-2c5048e4fc02.sized-1000x1000.JPG?",
        "stmt": "HALLA!! My name is Sravya Alla, and I am running to be one of your eight New Student Representatives in the Undergraduate Assembly! During NSO, when people did not have anything the talk about, the default conversation was either weather or complaints. “The showers are disgusting!” “It’s not fair that I have to pay for printing” “Why can I not use dining dollars here?” Unfortunately, there’s a lot of things to complain about and for good reason too, but nothing is done about them. I like to think of myself as a person of action (unbiased statement) so I am running to transform these thoughts into substantial impact. My unoriginally cleverly-titled campaign ALLA has four components. A: All schools, One Penn. I believe that every undergraduate school should be equal and that includes free printing services and access to all public computers. L: Launching a Quad Hygiene Initiative with hand sanitizer dispensers because freshmen dorms are disgusting. L: Longer dining hours and more dining dollar venues because food is life. And lastly, A for ACTION! Support Sravya for UA and HALLA FOR ALLA!"
      },{
        "name": "Ammar Bawa",
        "photo": "https://snworksceo.imgix.net/dpn/9fb6ea48-1954-44ce-a2ea-1f00a337ee1e.sized-1000x1000.JPG?",
        "stmt": "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.” - Benjamin Franklin. Since our University’s inception, growth and development have been vital in establishing our University as one of the top institutions in the nation, yet we still have potential for more growth and development in student-university interaction and student wellness. My name is Ammar, and as your New Student Representative in the UA, I would focus on:“Without continual growth and progress, such words as improvement, achievement, and success have no meaning.” - Benjamin Franklin. Since our University’s inception, growth and development have been vital in establishing our University as one of the top institutions in the nation, yet we still have potential for more growth and development in student-university interaction and student wellness. My name is Ammar, and as your New Student Representative in the UA, I would focus on: Educational Accessibility: Increasing awareness, prevalence, and availability for on-campus, university-sponsored tutoring through supplemental instruction, three-day bootcamps at the beginning of the semester for content familiarization, and tutoring for upper-level classes with high student enrollment. Financial Accountability: Providing assistance for unaccounted enrollment costs, such as student insurance, and addressing rising tuition costs, availability of financial-aid advising, and financial compliance to all students’ needs. Student Input: Making opportunities for student involvement more transparent in the legislative branch by actively pursuing students’ opinions and concerns within the University. Dining Flexibility: More options for dining dollar use and establish new meal swipe equivalencies for participating restaurants. Extracurricular Intensity: Reduce intensity standard for clubs and organizations and implement incentives for clubs to comply to the standard."
      },{
        "name": "John Casey",
        "photo": "https://snworksceo.imgix.net/dpn/8581ed3e-ca9f-4ca5-8cdd-163b22b59a5b.sized-1000x1000.JPG?",
        "stmt": "I had no idea what NSO was going to be like, and Hollywood definitely distorted my view of college. I thought everyone drank; I thought everyone partied. I wanted to fit the mold. The first day of NSO, I met with friends in a dorm room and took shots of Vodka. We were stupid; we left the window blinds open. Within minutes, there was a knock at the door. It was an RA. I frantically searched for a hiding spot. I even considered lunging for the closet. I decided against it; we let the RA in, and I mentally packed my dorm… my roommate was going to love his new single. “I’m not superstitious, but I’m a little stitious” --Michael Scott. I believe the universe sends signs. To me, getting caught with alcohol was a sign that I shouldn’t try to be someone I’m not. The real John Casey collects campaign buttons. The real John Casey loves Migos and Kendrick. The real John Casey cares about issues like financial aid and club competitiveness at Penn. ‘NSO John’ was an idiot (who gets caught drinking in the Quad???)... vote for The real John Casey instead."
      },{
        "name": "Will Castner",
        "photo": "https://snworksceo.imgix.net/dpn/4abfcff1-2e0b-43db-9609-3029c0fe6513.sized-1000x1000.JPG?",
        "stmt": "Hello Penn class of 2021 and transfers! With the elections for Penn’s 2017-18 Undergraduate Assembly quickly approaching, I wanted to tell the class a little about myself. My name is Will Castner and I am from Sidney, Nebraska. Before applying ED to Penn, I thought I had a grasp on Penn’s academics and student life. However, after moving to campus in August, my expectations for the university were far surpassed. It only took a few days on campus to instill a passion about Penn and it’s unmatched student life and culture. Penn is the perfect crossroads between academia and community, ambition and joy, intelligence and humility. Nonetheless, I believe anything can be improved. If elected to the undergraduate assembly, I will use my passion for Penn to work with the rest of the assembly, and the greater student body, to make this university the best it can be. Coming from a rural background, I have a different perspective of this urban campus;  A different view of any situation is beneficial.  Similarly to every other candidate for Undergraduate Assembly, I have the necessary leadership skills and experiences. I believe my passion and unique perspective on Penn’s culture is what sets me apart. "
      },{
        "name": "Charles Curtis-Thomas",
        "photo": "https://snworksceo.imgix.net/dpn/497768f8-4f4d-4c9f-8ecd-e9e29c19685d.sized-1000x1000.JPG?",
        "stmt": "Hey everyone! My name is Charles Curtis-Thomas and I’m running for UA and College Class Chair. I’ve gotten to meet many of you over the past few weeks and share my ideas with you, and I know I made the right choice coming to Penn. 10, 20, even 30 years from now, I want to look back on the Class of 2021 as the greatest class in Penn’s history. I want our class to produce future economists, future nurses, future impactors, and future world changers. On the College side, I have noticed that there are many intra-school activities that involve the other three schools, but not many specifically for the College, which has the largest collection of students. I intend to change this, and create fun activities for College students. Finally, I plan to fix problems around our campus, such as implementing central cleaning stations to deal with bugs, implementing more water filling stations, finally putting accessible trash cans around the Quad and other college houses, and more. I’m excited to work with you to help improve our already impressive community. If you want Penn to be the best it can be, express your right and vote for CCT."
      },{
        "name": "Jude Dartey",
        "photo": "https://snworksceo.imgix.net/dpn/ba70b35c-bcbf-4fd9-8e5e-e0bb97ae60fb.sized-1000x1000.JPG?",
        "stmt": "My role as President will be very simple: I will be an advocate for the Class of 2021. I am not a person who makes promises that I can’t keep, so I will use this medium to tell you a little bit about myself. I was born and raised in Ghana, West Africa. My family settled in America when I was 11. I spent the first few years in America figuring out how to fit in with others and I plan to use that experience to make our class inclusive to the point where everyone feels welcome. I am also a first generation, low income student. While some might argue that this comes at a disadvantage; I argue that my identity has taught me to use the most of the resources that are given to me. I do not put anything to waste. I am confident that I can use every ounce of every single resource available to me to fabricate your desires into existence. I am very aware that I cannot earn this position without the votes of the class so my first and only priority as President will be to serve as the voice behind your vision on how this class should be run. I recently walked into King’s Court English House dining hall to grab dinner with my best friend. His choice of dining is limited to King’s Court given that he keeps halal. After swiping his card, he was informed that no halal food was available for him that day. I saw the frustration in his eyes as he exited the dining hall having wasted a swipe. I  immediately understood his rage because he is paying for a dining plan but is not guaranteed a full meal everyday. This incident was my motivation to run for a position on the Undergraduate Assembly (UA). All great things in this world have their faults. My goal as a member of the UA will be to highlight these faults on campus and alter them to for the betterment of our campus community. Perfection does not exist on earth, but we can TRY to attain it within our campus one step at a time. That first step is to cast your vote for Jude Dartey."
      },{
        "name": "Jesse Fox",
        "photo": "https://snworksceo.imgix.net/dpn/450f8d66-651f-4448-a2cf-a6f2890706a0.sized-1000x1000.JPG?",
        "stmt": "My name is Jesse Fox and I hope that you, the students of the University of Pennsylvania, will elect me to the Undergraduate Assembly (UA). As a member of the UA, I hope to make lasting and impactful changes to campus. For example, as a member of the representative branch of Penn’s student government, I will lobby for more recycling bins around campus. Also, I will double the number of washers and driers in all the buildings on campus. Finally, I will always have my ears open to the needs and wants of the students. The UA directly interacts with administration and oversees that allocation of approximately $2 million. For that reason, we will be able to get stuff done! Therefore, any changes people want to see, they can bring them to me and I will serve as their champion. So, remember, vote me, Jesse Fox, for one of the UA’s new student positions."
      },{
        "name": "Sam Goidell",
        "photo": "https://snworksceo.imgix.net/dpn/7c688cb3-cd26-4c94-ba06-8940b2b96bf9.sized-1000x1000.JPG?",
        "stmt": "No, I won’t hit you with gimmicks. Nor will I wow you with smoke and mirrors or fancy tricks. Instead, my platform is simple: what you see is what you get. A guy named Sam who misses the delicious taste of In-n- Out burger. But more importantly you will get an advocate. My only goal as a member of the Undergraduate Assembly will be to make sure the ideas, issues, and opinions of our class are represented at every step of the way. And, I believe I have the necessary experience to make this happen. I have worked as a lobbyist at the California State Capitol representing and advocating for students’ rights with true success; just this past year two of my bills passed the legislature and are on the governor’s desk. My background working with legislators will translate directly into action when I collaborate with my fellow members of the Undergraduate Assembly to advocate for necessary campus reforms with President Gutmann and the rest of the Penn administration."
      }, {
        "name": "Connor Hart",
        "photo": "https://snworksceo.imgix.net/dpn/375a4645-ed76-4653-b4e6-e9defa216b58.sized-1000x1000.JPG?",
        "stmt": "Hello, my name is Connor Hart and I am running to be a new student representative in the Undergraduate Assembly. Some information about me. I am literate. I am a student at Penn. I enjoy long walks on the beach. My favorite fruit is the peach and my spirit animal a moose. Now, it has only been a couple weeks since we started our careers here at Penn, but a few issues have already become clear. Currently, my primary objectives are the creation of an official campus-wide book trading program, an increase in funding for the freshman class, and an extensive review of dining hours. Of course, this is not an all-inclusive list, so to better facilitate bringing your ideas into action, I would also like to see an online system put in place for your suggestions to be heard by the UA beyond the current options. For more information on these topics, feel free to contact me at connorhart4rep@gmail.com. If you like these ideas, or just find me to be a groovy guy, vote for me. I look forward to meeting as many of you as possible and serving you in the Undergraduate Assembly."
      },{
        "name": "Jesse Liu",
        "photo": "https://snworksceo.imgix.net/dpn/912ce6ec-c20a-4518-a119-d008df368179.sized-1000x1000.JPG?",
        "stmt": "Hello, I’m Jesse Liu and I am running to be your Freshmen Class Executive Vice-President! I am originally from Rolla, Missouri and I want to try my best to ensure that your freshmen class experience here at Penn is fulfilling and fun, in and out of the classroom. I will work to not only try and serve as a voice to represent your interests on the class board, but I will work to promote class participation in the class board and in student government as a whole. We all worked hard to get here and we all deserve a voice in how the school is run! If elected, I will advocate for the creation of a platform where any freshmen can write suggestions to the class board for events and activities that other freshmen want to be a part of and I will also push for the addition of more options for dining dollars and swipes on campus, while also working with my peers on the class board to try and make more freshmen events. Let’s come together and create change on this campus. Remember, if you want a good voice for you, vote Jesse Liu! "
      },{
        "name": "Vanessa Lundstrom-Placencia",
        "photo": "https://snworksceo.imgix.net/dpn/ca8a1dac-c9a0-408e-a993-5c57ebbf522c.sized-1000x1000.JPG?",
        "stmt": "Hi, I’m Vanessa Lundstrom-PLacencia! Thank you for considering me to be your next representative. Representing the student body is not a role to be taken lightly and each and every one of the decisions made on my behalf will be centered on the best interest of my classmates, the University of Pennsylvania Class of 2021. My closest friends would describe me as an effective communicator and leader who is not afraid to get my hands dirty. I am ready to voice both your proposals and concerns. Come share your ideas and I will make them happen. PSA: There is no ‘L’ in Vanessa, so go for the ‘W’ and vote for VANESSA!!!!"
      },{
        "name": "Sahitya Mandalapu",
        "photo": "https://snworksceo.imgix.net/dpn/ddc1e793-e1cb-4c00-a2c3-8eb4bac5d995.sized-1000x1000.JPG?",
        "stmt": "Hi everyone! My name is Sahitya Mandalapu, but call me Sith! I’m running for Vice President of Finances and the Undergraduate Assembly. I’m from Bethlehem, PA and I’m in Wharton studying Finance and Public Policy. As class president of my high school, I absolutely loved planning events for my peers. After planning homecomings, formals, and even a 12-hour dance marathon, I loved seeing the smiles of my peers and watching them come together as a class. If you have ideas for awesome events besides the traditions (like Econ Scream, Hey Day, etc.), I would love to hear them and present them to the rest of the Class Board. I really want to be our VP of Finances to continue my passion for social and event planning and connecting with my classmates. And as I study Finance, I think I will be great at managing our class’ spending and fundraising. I love meeting people so I urge you to say hi and introduce yourself if you see me! I want to be your VP of Finances, your friend, and your voice!! I stand behind my class and hopefully you’re with me too #ImWithSith "
      }, {
        "name": "Ben May",
        "photo": "https://snworksceo.imgix.net/dpn/6664cb77-723f-491c-9d09-0a8da9d0fed7.sized-1000x1000.JPG?",
        "stmt": "Hello, I’m Ben May. I’m extremely extroverted and plan on trying to meet everyone in the Class of 2021 to best represent your interests in the Undergraduate Assembly. I aim to engage and excite the class to bring about positive change. My experience in policymaking includes presenting to the United Nations, meeting with the White House, and spearheading local movements to bring about political reform. I intend on increasing transparency within the Undergraduate Assembly by streamlining communications to UA representatives regarding issues you want solved. I will work towards making it easier to audit courses and preventing classes from becoming overbooked (let’s agree, the floor does not count as a desk). Additionally, I will lobby for increased access to water fountains and ice machines. I will press for increased sustainability on campus through a university-wide compost bin system and a stronger recycling program. I have already gotten in contact with current UA representatives and the Registrar Office to get these policies passed. Vote Ben May for UA!"
      },{
        "name": "Mercedes Owens",
        "photo": "https://snworksceo.imgix.net/dpn/0b82ede9-9802-4a7a-a0f1-d5e1a5395fe8.sized-1000x1000.JPG?",
        "stmt": "My name is Mercedes Owens, yes like the car. The name is not the only similarity. The Mercedes-Benz slogan is “the best or nothing,” which is exactly what I represent. I want the best for everyone at Penn, and I am willing to put forth my best effort in order to attain the greatest results. When the Board of Trustees of Penn established the UA, they charged it with improving life for all students through funding, services, and advocacy. If elected, I fully intend to expand the bounds of life at Penn and to create an environment of love and support for all students, regardless of race, class, or sexuality. UA would allow me to advocate for those who are at a disadvantage upon arriving at Penn. As a first-generation low-income student (FGLI), I understand the struggles of acclimating to an environment where everyone around you is aware of the numerous opportunities Penn provides. I want to raise awareness of the many resources offered not only for FGLI students, but for those who feel emotionally or culturally disadvantaged as well. Penn is a place of opportunity; you just have to know how to find it, and I want to help!"
      },{
        "name": "Ravi Rakesh",
        "photo": "https://snworksceo.imgix.net/dpn/70b04afc-716e-48ff-bc32-31387e6b6649.sized-1000x1000.JPG?",
        "stmt": "A member of the Undergraduate Assembly must have the passion and determination to push Penn forward by embodying its age-old spirit and creating tangible change in the lives of students. Penn is special because we are encompassed by its commitment to collaboration and engagement. As a member of the UA, I will push that commitment even further. I would work towards cultivating more classes and programs where students are able to weave different disciplines together while further engaging with their peers in the classroom. Analyzing principles of physics through dance or studying community psychology through sports history allows students to explore their interests in unconventional ways and provides them with opportunities to engage with more students outside their discipline. Not only do I wish to make learning more collaborative but also impactful. By working to create more Academically Based Community Service classes that cover a range of student interests from engineering to theater, all Penn students should have the opportunity to engage with their community in a way that intrigues them. Penn students have a diverse set of interests and my mission would be to help them pursue all of their passions. "
      },{
        "name": "Bradley Saunders",
        "photo": "https://snworksceo.imgix.net/dpn/d8da10f8-0e8c-4659-bf24-34d6d53750d4.sized-1000x1000.JPG?",
        "stmt": "What if Wawa took dining dollars? Hello Penn freshmen. My name is Brad Saunders, and I’m running for UA New Student Representative. My platform is simple: making life better for everyone at Penn. Whether it’s expanding eateries on campus, lobbying for more half credit classes, or getting Insomnia Cookies to accepting dining dollars (it’s literally in Houston Hall), my initiatives center around improving student quality of life here at our home. I have ample prior experience with leadership and activist positions, having worked on a political campaign for nine months and subsequently co-founding the first political club at my high school. While Penn is a world-class institution, there are always improvements that can be made. As a resident of Hill, I’ve heard numerous complaints regarding the relative quality at other dining halls. There’s no reason that the fantastic food quality at Hill can’t be enjoyed at every dining hall on our campus. I can and will, as a New Student Representative, work tirelessly to ensure that your voice is heard at our school. My door is always open and I value everyone’s input. Feel free to contact me with any questions or ideas! Thank you.<br><br>-  Brad Saunders"
      }, {
        "name": "Sophia Schulz-Rusnacko",
        "photo": "https://snworksceo.imgix.net/dpn/2b18d7ae-10f7-47b8-a85d-d1923b0fd457.sized-1000x1000.JPG?",
        "stmt": "Hi! My name is Sophia Schulz-Rusnacko and I’m a freshman from Minneapolis, Minnesota. As Class of 2021’s Nursing Chair, I want to serve a liaison between the School of Nursing and the other three undergraduate schools. Nursing is sometimes overlooked or forgotten about because we are so small, so I want to bridge the gap between schools while also educating non-nurses about what we do! In Nursing 101, we’re learning about the stigma and stereotypes surrounding nursing, and as Class Chair, I would love to educate the entire Penn population about nursing’s REAL role in healthcare and society."
      }, {
        "name": "Chase Serota",
        "photo": "https://snworksceo.imgix.net/dpn/9260f3c9-10cb-45d2-ba0d-0a4360abe931.sized-1000x1000.JPG?",
        "stmt": "As a UA Representative, I will strive to put the UA to work for you. I promise to be easily accessible and to be a strong advocate for your most pressing concerns. Student Government has always been a passion of mine––I served as President of my high school's Student Council from my freshman through senior years. I have seen firsthand that, with the right leaders in place, Student Government can achieve tangible change. As President of my high school, I worked to create the first-ever Student Representative Seat on my school district's Board of Education. I hope to continue similar work here at Penn, advocating for fellow students at all levels. One of my goals as a member of the UA is to expand mental health resources on campus. I will work to increase support and funding for CAPS and communicate the prevalence of stress, anxiety and depression among our student body. Ultimately, I hope to create an environment where students are better equipped to help each other combat mental health issues. At Penn, your wellness should come first, and that’s exactly what I plan on communicating if elected. "
      },{
        "name": "Kristen Ukeomah",
        "photo": "https://snworksceo.imgix.net/dpn/f4275a50-dee2-4983-ac03-d895204e6cc9.sized-1000x1000.JPG?",
        "stmt": "If you’re reading this statement, I am the one you’ve been searching for. It is I.<br><br>But on a serious note:<br><br>The University of Pennsylvania is a very diverse campus, with people of several different races, ethnicities, nationalities, sexual orientations, religions, socioeconomic backgrounds and more. My main platform consists of ensuring that all of this diversity is represented, accounted for, and advocated for on the Undergraduate Assembly. Although Penn’s administration does its role to ensure equal access to opportunities for all their students, the best way to know what students lack is to work with those affected students, so I believe it is important for members of minority groups to assume positions of leadership like this. Because I don’t represent every minority group on campus, my plan is to reach out to many student groups on campus, like the United Minorities Council, Lambda Alliance, and Penn First, just to name a few, and build a bridge between them and the UA, or strengthen it if this channel of communication exists already. And this just one of my many ideas.<br>Hopefully, you’re nodding your head because you vibe with the vision. Look no further, I’m your candidate."
      },{
        "name": "Daniel Wittmer",
        "photo": "https://snworksceo.imgix.net/dpn/910786a3-ed75-438a-b4fc-0e47421910ec.sized-1000x1000.JPG?",
        "stmt": "I want to be your Vice President of Internal Affairs pure and simple, and I’ll tell you why. I come from a small rural town in Kentucky where I grew up on a farm performing the stereotypical farming practices. Hoeing the garden, feedin' the cattle you name it. With this upbringing, southern hospitality and attentive listening are traits that I’ve acquired. I want to be an outlet for every single one of you, by truly hearing your ideas. As VP of Internal Affairs, my main duty is to set agendas for and plan board meetings. That's why I want to develop an online open discussion platform for the class of 2021 to write ideas and have peers vote on the significance of the idea. I can then take these important issues and make them the top priority at our board meetings for discussion. I came to Penn to learn about people from every background imaginable, so if you have any questions for me my campaign Instagram is bigD4VP. You can add me on all of my social media outlets from there! Thank you, God Bless, and vote Big Dan for Internal Affairs VP. "
      },{
        "name": "Victoria Wu",
        "photo": "https://snworksceo.imgix.net/dpn/96e7dc90-1a4d-4bf1-a6b6-5bcc5a6a6673.sized-1000x1000.JPG?",
        "stmt": "Hey Class of 2021! My name is Victoria Wu and I would like to be your Class Board Executive Vice President. The decision to attend college is a big time-commitment as well as a huge financial decision. We all know Penn costs a fortune. But we all decided to come here because we believed that it was worth the cost. Spanning all fifty states and over ninety-four countries, we have the opportunity to learn and meet new people of all different backgrounds and cultures. While we work hard in our academics, we’ll need study breaks along the way! I hope to provide a wide variety of social activities for the student body to bring everyone together and make our huge campus feel like a close-knit community.<br>Vote for VWu for VP!"
      }, {
        "name": "Shaina Zafar",
        "photo": "https://snworksceo.imgix.net/dpn/aa3e1a1a-af15-46d3-b0bb-6b6fc2872ecc.sized-1000x1000.JPG?",
        "stmt": "Hello fellow Quakers,<br> My name is Shaina Zafar and I’m running as New Student Representative for Penn’s Undergraduate Assembly! Through my Freshman weeks at Penn, it’s clear that people here build connections, think freely, and grow both, academically and personally. Penn truly thrives because of its communities—the people. Through inclusivity, my platform aims to ensure that students at Penn can be comfortable regardless of their personal background. There’s a disproportionate amount of people who utilize and are aware of campus resources. This is where student curated content, resource guides, and subsidized resources can serve marginalized communities like FGLI students. With an emphasis on transparency, mental health awareness must be a priority on campus. We must foster a collaborative academic community through group mentorships in campus spaces, have student run forums, and effectively voice the concerns of the student body to Penn’s institutions. I will ensure that the UA’s efforts support the needs of students, both those currently attending the university and those who will come here in the future. This means restructuring future NSO events, decreasing the costs of campus events and traditions, and allowing students to tangibly provide feedback for improvement. It’s time to give UA seat at the table.<br>Call me, beep me if you want to reach me!<br>Facebook: fb.me/ShainaForUA<br>Email: shainaz@sas.upenn.edu"
      }, {
        "name": "Alex Zhang",
        "photo": "https://snworksceo.imgix.net/dpn/87fc4a19-159a-461c-ab06-a3a5d29ef6b2.sized-1000x1000.JPG?",
        "stmt": "Hi, everyone! My name is Alex Zhang, and I’m running for New Student Representative in the Undergraduate Assembly (UA). Although Penn has been exciting for these past few weeks, there can definitely be some improvements. As New Student Representative, I hope to address these certain issues: dining halls currently close too early, there are too few water filling stations, food trucks don’t accept Penn Dollars (food trucks taste too good for dining dollars not to be accepted), there are too few showers, and the current showers are way too small. Also, printing should be free.<br><br>All of my goals are straightforward and tangible, and I know that I can achieve them. Proposing goals that I can achieve is very important to me. For example, when I was Vice President in my high school, I proposed to install phone charging stations, and within a month, phone charging stations were available across my school. When I was President of my class, I said that I would have umbrellas across the school for public use; by the end of the year, students could walk from building to building without being rained on. <br> A vote for Alex is a vote for tangible change."
      }, {
        "name": "Kevin Zhou",
        "photo": "https://snworksceo.imgix.net/dpn/81eae395-e33e-43da-8592-d6e223ad9c94.sized-1000x1000.JPG?",
        "stmt": "Hey y’all, my name is Kevin Zhou, your favorite magician who goes around entertaining people at dinner times. Magic might be a noticeable character of mine but it is definitely not the most defining: I wear Crocs AND socks and luckily it hasn’t stopped (most) people from befriending me. As weird as I am, student government is my biggest passion and something that I dedicate to seriously. As an immigrant who moved to the U.S. in middle school, everything I have achieved would’ve never happened without the friends and family who supported me through every step. I know I am fortunate and I am thankful, and student government has been my most direct outlet to express that gratitude. If I am elected, I plan on adding more water fountains and trash cans to the quad, fixing the AC problem in English, emphasizing quality over quantity for food in most dining halls, adding Joe Biden Sighting Alert on PennMobile, and most importantly, hearing you guys out as much as possible. I am here to serve because my happiness stems from the satisfactions of others, so vote Kevin Zhou for UA, and I promise to work my magic ;)"
      }
    ]
  }
};

$(document).ready(function() {
  var ua = people.ua;
  var cb = people.cb;

  var loadList = function(people, listID) {
    for (var person in people) {
      $('#'+listID).append("<li>" +
          "<figure>" +
              "<img src='" + people[person].photo + "'>" +
              "<figcaption>" +
                "<h3>" + people[person].name + "</h3>" +
                "<p>" + people[person].stmt + "'</p>" +
                "<a href='https://www.pennstudgov.com'>Vote Here</a>&nbsp;" +
              "</figcaption>" +
              "<h3>" + people[person].name + "</h3>" +
          "</figure></li>"
      );
    }
  }

  loadList(cb["President"], "ua-list");
  loadList(cb["Executive_Vice_President"], "ua-vp-list");
  loadList(cb["College_Chair"], "ua-sas-rep");
  loadList(cb["Engineering_Chair"], "ua-seas-rep");
  loadList(cb["Wharton_Chair"], "ua-wharton-rep");
  loadList(cb["Nursing_Chair"], "ua-nursing-rep");
  loadList(cb["Vice_president_of_External_Affairs"], "ua-vp-ext");
  loadList(cb["Vice_president_of_Finances"], "ua-vp-fin");
  loadList(cb["Vice_president_of_Internal_Affairs"], "ua-vp-int");
  loadList(ua["New_Student_representative"], "ua-nsrs");

  var lists = $('.cs-style-1');

  var randomize = function(x) {
    for (var i = x.children.length; i >= 0; i--) {
      x.appendChild(x.children[Math.random() * i | 0]);
    }
  }

  for (var list in lists) {
      randomize(lists[list]);
  }

});
